# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae728bf2db41c67b410e4347f2f2d4996adc30197192f9638950df965370515a91ba20fe0fbceca28727d137098018ed63a39f3a3eff27944fbb03f2fab0564e

test:
  secret_key_base: 20ffdb6853029857c6d1a5f110e56091460dac74fce570422620224e98d8099dadb86e96754c211ff80f3c1c95c3d7e8b13c75bca440a5d94decc6f0c2be6f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
